name: Daily Random Matter Article

on:
  # schedule:
    # - cron: '0 0 * * *' # Runs the job every day at midnight UTC
  workflow_dispatch: # allow for manual trigger

jobs:
  send-email:
    runs-on: ubuntu-latest

    env:
      EXA_API_KEY: ${{ secrets.EXA_API_KEY }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: troubleshooting
        run: |
          length=$(echo -n "$RESEND_API_KEY" | wc -c)
          echo "Length of RESEND_API_KEY: $length"

      - name: Install dependencies
        run: cd ./random-article-node && yarn
  
      - name: Run script
        run: cd ./random-article-node && yarn start
