name: Weekly Product

on:
    schedule:
      - cron: '0 5 * * 1-5' # Runs the job every weekday at 5 AM UTC
    workflow_dispatch: # allow for manual trigger

jobs:
    send-weekly-product:
        runs-on: ubuntu-latest
        environment:
            name: Production

        env:
            EXA_API_KEY: ${{ secrets.EXA_API_KEY }}
            RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - uses: oven-sh/setup-bun@v2

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '18'

            - name: Install dependencies
              run: yarn

            - name: Run script
              run: bun experiments/products/index.ts
