name: PR Checks

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install
        run: yarn

      - name: compile
        run: yarn compile

      - name: test
        run: yarn test

      - name: lint
        run: yarn lint
