name: Weekly Readwise Sync

on:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:

jobs:
  weekly-readwise-sync:
    runs-on: ubuntu-latest
    environment:
      name: Production

    env:
      EXA_API_KEY: ${{ secrets.EXA_API_KEY }}
      READWISE_API_TOKEN: ${{ secrets.READWISE_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: yarn

      - name: run script
        run: npx ts-node sources/readwise-reader/sync.ts

      - name: Commit changes
        run: |
          git config --global user.email "api-user@decision-making-experiments.com"
          git config --global user.name "Decision Making Bot"
          git status
          git add .
          git commit -m "Update Readwise JSON file via GitHub Actions"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
