name: Weekly Newsletter

on:
    schedule:
      - cron: '0 11 * * 6' # Runs the job every Saturday at 6:00 AM EST
    workflow_dispatch: # allow for manual trigger

jobs:
    send-weekly-newsletter:
        runs-on: ubuntu-latest
        environment:
            name: Production

        env:
            EXA_API_KEY: ${{ secrets.EXA_API_KEY }}
            RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
            READWISE_API_TOKEN: ${{ secrets.READWISE_API_TOKEN }}
            REFLECT_ACCESS_TOKEN: ${{ secrets.REFLECT_ACCESS_TOKEN }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - uses: oven-sh/setup-bun@v2

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '18'

            - name: Install dependencies
              run: yarn

            - name: Run script
              run: bun experiments/newsletter/index.ts
