name: Weekly Book

on: 
    schedule: 
        - cron: '0 20 * * 0'
    workflow_dispatch: 

jobs:
    send-weekly-book:
        runs-on: ubuntu-latest
        environment: 
            name: production
        
        env: 
            RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup node.js
              uses: action/setup-node@v4

            - name: Install dependencies
              run: cd ./random-book-node && yarn

            - name: Run script
              run: cd ./random-book-node && yarn start
            